Repository anitab-org/stem-diverse-tv-cms, pull requests merged in 2021-04, with the labels that each got.

#44 chore: add config.yml for welcome bot
  .github/workflows/config.yml
Labels: Status: Ready to Merge

#61 clean: Removed .github/ISSUE_TEMPLATE
  .github/CONTRIBUTING_GUIDELINES.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: Category: Quality Assurance, Status: Ready to Merge, open source hack

#63 chore: config all-contributors bot
  .all-contributorsrc
  README.md
Labels: Status: Needs Review

#66 Updated README.md as per the issue #65
  README.md
Labels: Status: Ready to Merge, open source hack
